PGraphics g; 
PImage temp; 
size(400, 400); 
g = createGraphics(width, height); 
color cBlue = color(40, 37, 124); 
colorMode(HSB); 
g.beginDraw(); 
g.noStroke(); 
g.rect(0, 0, width, height, 80); 
g.loadPixels(); 
for (int i = 0; i < width*height; i++) { 
  if ((g.pixels[i]!=color(0))&&(alpha(g.pixels[i]) > 50)) 
    g.pixels[i] = color(hue(g.pixels[i]), saturation(g.pixels[i]), brightness(g.pixels[i])-0.1*i/width);
}; 
g.updatePixels(); 
g.pushMatrix(); 
g.translate(width/2, height/2); 
g.scale(2.5); 
g.stroke(cBlue); 
g.strokeWeight(2); 
g.noFill(); 
g.line(width/3-width/2, height/2-height/2, width/2-width/20-width/2, height/2-height/2); 
g.line(width/2 + width/20 - width/2, height/2-height/2, 2*width/3-width/2, height/2-height/2); 
g.ellipse(width/2-width/2, height/2-height/2, width/10, width/10); 
g.stroke(cBlue); 
g.strokeWeight(1); 
g.ellipse(width/2-width/2, height/2-height/2, (width/30), (width/30)); 
g.popMatrix(); 
g.loadPixels(); 
g.endDraw(); 
image(g, 0, 0); 
temp = g.get(); 
temp.resize(36, 36); 
temp.save("D://Documents/icon-36.png"); 
temp = g.get(); 
temp.resize(48, 48); 
temp.save("D://Documents/icon-48.png"); 
temp = g.get(); 
temp.resize(72, 72); 
temp.save("D://Documents/icon-72.png"); 
temp = g.get(); 
temp.resize(96, 96); 
temp.save("D://Documents/icon-96.png"); 
temp = g.get(); 
temp.resize(144, 144); 
temp.save("D://Documents/icon-144.png"); 
temp = g.get(); 
temp.resize(192, 192); 
temp.save("D://Documents/icon-192.png");
